# Capain Praktikum 8

Diharapkan mahasiswa/i setelah mengikuti praktikum 5 - PBO, mampu memahami & mengimplementasikan :

1. Membuat Barang Service
2. Membuat Pegawai Service
3. Membuat Penjualan Service
4. Membuat Pembelian Service

https://kelasprogrammer.com/membuat-aplikasi-crud-web-python-mysql/

# Entitas

In [1]:
class Barang:
    
    def __init__(self, id_barang, nama_barang, kuantitas, harga_beli, harga_jual):        
        self.id_barang = id_barang
        self.nama_barang = nama_barang
        self.kuantitas = kuantitas
        self.harga_beli = harga_beli
        self.harga_jual = harga_jual
    
    def tampilkan_data_barang(self): 
        print("============Data Barang============")
        print("ID Barang:", self.id_barang)
        print("Nama Barang:", self.nama_barang)
        print("Kuantitas:", self.kuantitas)
        print("Harga Beli:", self.harga_beli)
        print("Harga Jual:", self.harga_jual)

class Pegawai:
    
    def __init__(self, id_pegawai, nama_pegawai, no_hp):        
        self.id_pegawai = id_pegawai
        self.nama_pegawai = nama_pegawai
        self.no_hp = no_hp
    
    def tampilkan_data_pegawai(self): 
        print("============Data Pegawai============")
        print("ID Pegawai :", self.id_pegawai)
        print("Nama Pegawai :", self.nama_pegawai)
        print("No HP :", self.no_hp)        
        
class Penjualan(Barang, Pegawai):
    def __init__(self, id_penjualan, barang, pegawai, tanggal_penjualan, kuantitas_jual):
        Barang.__init__(self, barang.id_barang, barang.nama_barang, barang.kuantitas, barang.harga_beli, barang.harga_jual)
        Pegawai.__init__(self, pegawai.id_pegawai, pegawai.nama_pegawai, pegawai.no_hp)
        
        self.id_penjualan = id_penjualan
        self.tanggal_penjualan = tanggal_penjualan
        self.kuantitas_jual = kuantitas_jual  
        self.harga_jual = barang.harga_jual
        self.jumlah = kuantitas_jual*barang.harga_jual
        
        print("==========Penjualan==========")
        print("waktu : ", self.tanggal_penjualan)
        print("Kuantitas jual : ", self.kuantitas_jual)
        print("Harga jual : ", self.harga_jual)
        print("Jumlah : ", self.jumlah)

        super().tampilkan_data_barang()
        super().tampilkan_data_pegawai()
        
class Pembelian(Barang, Pegawai):
    def __init__(self, id_pembelian, barang, pegawai, tanggal_pembelian):       
        Barang.__init__(self, barang.id_barang, barang.nama_barang, barang.kuantitas, barang.harga_beli, barang.harga_jual)
        Pegawai.__init__(self, pegawai.id_pegawai, pegawai.nama_pegawai, pegawai.no_hp)
        
        self.id_pembelian = id_pembelian
        self.tanggal_pembelian = tanggal_pembelian
        self.kuantitas_beli = barang.kuantitas
        self.harga_beli = barang.harga_beli
        self.jumlah = self.kuantitas_beli*barang.harga_beli

        
        print("==========Pembelian==========")
        print("Tanggal Pembelian : ",self.tanggal_pembelian)
        print("Kuantitas Beli : ",self.kuantitas_beli)
        
        super().tampilkan_data_barang()
        super().tampilkan_data_pegawai()

# Test Entitas

In [2]:
barang = Barang("2","Mie Sedap Soto Madura", 125, 1000, 1500)
#barang1.tampilkan_data_barang()

pegawai = Pegawai("2", "Hagoromo", "0812456789")
#pegawai1.tampilkan_data_pegawai()

penjualan = Penjualan("", barang, pegawai, "4 Maret 2021", 10)
print()

pembelian = Pembelian("", barang, pegawai, "4 Maret 2021", 10)

==========Penjualan==========
waktu :  4 Maret 2021
Kuantitas jual :  10
Harga jual :  1500
Jumlah :  15000
============Data Barang============
ID Barang: 2
Nama Barang: Mie Sedap Soto Madura
Kuantitas: 125
Harga Beli: 1000
Harga Jual: 1500
============Data Pegawai============
ID Pegawai : 2
Nama Pegawai : Hagoromo
No HP : 0812456789

TypeError: __init__() takes 5 positional arguments but 6 were given

# Barang CRUD

In [ ]:
import mysql.connector
import pandas as pd

class Barang_CRUD:

    def __init__(self, barang):  
        self.id_barang = barang.id_barang
        self.nama_barang = barang.nama_barang
        self.kuantitas = barang.kuantitas
        self.harga_beli = barang.harga_beli
        self.harga_jual = barang.harga_jual        
        
        conn = None

    @staticmethod
    def get_koneksi_db():
        conn = mysql.connector.connect(host="localhost" ,
                                            user="root",
                                            password="",
                                            database="warung")
        if conn.is_connected():
            print("Berhasil terhubung ke database")
        
        return conn

    def insert_data(self):
        koneksi_db = Barang_CRUD.get_koneksi_db()
        cursor = koneksi_db.cursor()
        
        sql = "INSERT INTO barang (nama_barang, kuantitas, harga_beli, harga_jual) VALUES (%s, %s, %s, %s)"
        val = (self.nama_barang, self.kuantitas, self.harga_beli, self.harga_jual)
        
        cursor.execute(sql, val)

        koneksi_db.commit()

        print("{} data ditambahkan".format(cursor.rowcount))
        Barang_CRUD.tampilkan_dataframe()
        
    def update_data(self):
        koneksi_db = Barang_CRUD.get_koneksi_db()
        cursor = koneksi_db.cursor()
        
        sql = "UPDATE barang set nama_barang=%s, kuantitas=%s, harga_beli=%s, harga_jual=%s WHERE id_barang=%s"
        val = (self.nama_barang, self.kuantitas, self.harga_beli, self.harga_jual, self.id_barang)

        cursor.execute(sql, val)

        koneksi_db.commit()

        print("{} data diupdate".format(cursor.rowcount))
        Barang_CRUD.tampilkan_dataframe()

    @staticmethod
    def delete_data(id_barang):
        koneksi_db = Barang_CRUD.get_koneksi_db()
        cursor = koneksi_db.cursor()
        
        sql = "DELETE FROM barang WHERE id_barang=%s"
        val = (id_barang, )
        cursor.execute(sql, val)

        koneksi_db.commit()

        print("{} data dihapus".format(cursor.rowcount))
        Barang_CRUD.tampilkan_dataframe()
            
    @staticmethod
    def tampilkan_dataframe():
        koneksi_db = Barang_CRUD.get_koneksi_db()
        sql = "SELECT * FROM barang"
        
        df = pd.read_sql(sql, con=koneksi_db)
        
        display(df)
    
    @staticmethod
    def tampilkan_satu_data(id_barang):
        koneksi_db = Barang_CRUD.get_koneksi_db()
        cursor = koneksi_db.cursor()

        sql = """SELECT * FROM barang where id_barang=%s"""
        val = (id_barang, )
        cursor.execute(sql, val)

        record = cursor.fetchall()
        
        barang1 = Barang(record[0][0], record[0][1], record[0][2], record[0][3], record[0][4])
        return barang1
    
        """
        #print(record[0][0], record[0][1], record[0][2], record[0][3], record[0][4])
        for row in record:
            print("ID Barang = ", row[0], )
            print("Nama Barang = ", row[1])
            print("Kuantitas = ", row[2])
            print("Harga Beli  = ", row[3])
            print("Harga Jual  = ", row[4], "\n")
        """

# Test Barang CRUD

In [ ]:
#barang = Barang_CRUD.tampilkan_satu_data(2)
#barang.tampilkan_data_barang()

#Barang_CRUD.tampilkan_dataframe()

#barang1 = Barang("","Mie Sedap Soto Madura", 125, 1000, 1500)
#Barang_CRUD(barang1).insert_data()

#barang1 = Barang("2","Mie Sedap Bakso", 125, 2000, 2500)
#Barang_CRUD(barang1).update_data()

#Barang_CRUD.delete_data(43)